# Generated by Django 4.2.18 on 2026-04-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20260330_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="user",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
