# Generated by Django 4.2.18 on 2026-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_outdoor",
            field=models.BooleanField(default=True),
        ),
    ]
